site_name: SQLY
site_url: https://kruxia.github.io/sqly
repo_name: kruxia/sqly
repo_url: https://github.com/kruxia/sqly
copyright: Copyright Â© 2023 by <a href="https://github.com/kruxia" target="_blank">Kruxia</a>.
watch:
  - sqly
theme:
    name: material
    # features:
    # - content.code.annotate
    # - content.code.copy
plugins:
  - mkdocstrings
  - search
markdown_extensions:
  - extra
  - mkdocs-click
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      linenums: false
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - smarty
  - toc:
      permalink: true
      permalink_title: Anchor link to this section
